"""initial schema

Revision ID: d2f4e604b336
Revises: 
Create Date: 2026-08-23 10:01:03.927859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f4e604b336'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purpose', sa.Enum('DAILY_FEEDBACK', 'WEEKLY_SUMMARY', 'DAILY_MESSAGE', 'GOAL_RETROSPECTIVE', name='aipurpose', native_enum=False), nullable=False),
    sa.Column('conversation_uid', sa.Text(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('prompt_chars', sa.Integer(), nullable=True),
    sa.Column('was_truncated', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_log', schema=None) as batch_op:
        batch_op.create_index('ix_ai_log_created_at', ['created_at'], unique=False)

    op.create_table('app_setting',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.Enum('STRING', 'INTEGER', 'FLOAT', 'BOOLEAN', 'JSON', name='appsettingvaluetype', native_enum=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('calendar_day_override',
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('day_type', sa.Enum('PLAN', 'BUFFER', 'OFF', name='daytype', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('target_date')
    )
    op.create_table('daily_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_date')
    )
    op.create_table('daily_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('record_state', sa.Enum('PROGRESS_ONLY', 'REPORTED', name='recordstate', native_enum=False), nullable=False),
    sa.Column('diary_body', sa.Text(), nullable=True),
    sa.Column('diary_learned', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_date')
    )
    op.create_table('day_type_default',
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('day_type', sa.Enum('PLAN', 'BUFFER', 'OFF', name='daytype', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('weekday')
    )
    op.create_table('goal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'CLOSED_WITH_RESULT', 'CLOSED_WITHOUT_RESULT', name='goalstatus', native_enum=False), nullable=False),
    sa.Column('resource_ratio', sa.Float(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holiday',
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('holiday_date')
    )
    op.create_table('prompt_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_customized', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purpose')
    )
    op.create_table('resource_slot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('environment', sa.Enum('ANY', 'PC', 'MOBILE', name='environment', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_conversation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.Enum('DAILY_FEEDBACK', 'WEEKLY_SUMMARY', 'DAILY_MESSAGE', 'GOAL_RETROSPECTIVE', name='conversationscope', native_enum=False), nullable=False),
    sa.Column('scope_key', sa.Text(), nullable=False),
    sa.Column('conversation_uid', sa.Text(), nullable=False),
    sa.Column('folder_uid', sa.Text(), nullable=True),
    sa.Column('last_parent_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'scope', 'scope_key', name='uq_ai_conversation_goal_scope_key')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('daily_record_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='chatrole', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_record_id'], ['daily_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index('ix_chat_message_record_sequence', ['daily_record_id', 'sequence'], unique=False)

    op.create_table('exam_subject',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exam_date_type', sa.Enum('RANGE', 'FIXED', name='examdatetype', native_enum=False), nullable=False),
    sa.Column('exam_date_from', sa.Date(), nullable=True),
    sa.Column('exam_date_to', sa.Date(), nullable=True),
    sa.Column('exam_date_fixed', sa.Date(), nullable=True),
    sa.Column('passing_score', sa.Float(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_subject', schema=None) as batch_op:
        batch_op.create_index('ix_exam_subject_goal_id', ['goal_id'], unique=False)

    op.create_table('goal_retrospective',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_anonymized', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal_retrospective', schema=None) as batch_op:
        batch_op.create_index('ix_goal_retrospective_goal_generated', ['goal_id', 'generated_at'], unique=False)

    op.create_table('load_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('load_profile', schema=None) as batch_op:
        batch_op.create_index('ix_load_profile_goal_period', ['goal_id', 'date_from', 'date_to'], unique=False)

    op.create_table('material',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit_label', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('planned_cycles', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('due_date_is_manual', sa.Boolean(), nullable=False),
    sa.Column('required_block_minutes', sa.Integer(), nullable=True),
    sa.Column('required_environment', sa.Enum('ANY', 'PC', 'MOBILE', name='environment', native_enum=False), nullable=False),
    sa.Column('quality_metric_type', sa.Enum('NONE', 'OBJECTIVE', 'SELF_SCORED', 'SUBJECTIVE', name='qualitymetrictype', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.create_index('ix_material_due_date', ['due_date'], unique=False)
        batch_op.create_index('ix_material_goal_id', ['goal_id'], unique=False)

    op.create_table('record_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('daily_record_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_record_id'], ['daily_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('record_comment', schema=None) as batch_op:
        batch_op.create_index('ix_record_comment_daily_record_id', ['daily_record_id'], unique=False)

    op.create_table('resource_slot_weekday',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['resource_slot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id', 'weekday')
    )
    op.create_table('weekly_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('summary_body', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'week_start_date', name='uq_weekly_summary_goal_week')
    )
    op.create_table('exam_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('taken_date', sa.Date(), nullable=False),
    sa.Column('result', sa.Enum('PASS', 'FAIL', 'PENDING', name='examresulttype', native_enum=False), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('evaluation', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['exam_subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id')
    )
    op.create_table('material_subject',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['exam_subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('material_id', 'subject_id')
    )
    with op.batch_alter_table('material_subject', schema=None) as batch_op:
        batch_op.create_index('ix_material_subject_subject_id', ['subject_id'], unique=False)

    op.create_table('plan_baseline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('baseline_daily_quota', sa.Float(), nullable=False),
    sa.Column('remaining_at_baseline', sa.Float(), nullable=False),
    sa.Column('plan_days_at_baseline', sa.Integer(), nullable=False),
    sa.Column('planned_cycles_at_baseline', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('INITIAL', 'REPLAN', 'EXAM_DATE_FIXED', 'MATERIAL_CHANGED', 'CYCLE_CHANGED', name='baselinereason', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_baseline', schema=None) as batch_op:
        batch_op.create_index('ix_plan_baseline_material_effective', ['material_id', 'effective_from'], unique=False)

    op.create_table('study_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('daily_record_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('minutes_spent', sa.Integer(), nullable=True),
    sa.Column('amount_completed', sa.Float(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('quality_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_record_id'], ['daily_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'daily_record_id', name='uq_study_log_material_record')
    )
    with op.batch_alter_table('study_log', schema=None) as batch_op:
        batch_op.create_index('ix_study_log_daily_record_id', ['daily_record_id'], unique=False)
        batch_op.create_index('ix_study_log_material_cycle', ['material_id', 'cycle_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_log', schema=None) as batch_op:
        batch_op.drop_index('ix_study_log_material_cycle')
        batch_op.drop_index('ix_study_log_daily_record_id')

    op.drop_table('study_log')
    with op.batch_alter_table('plan_baseline', schema=None) as batch_op:
        batch_op.drop_index('ix_plan_baseline_material_effective')

    op.drop_table('plan_baseline')
    with op.batch_alter_table('material_subject', schema=None) as batch_op:
        batch_op.drop_index('ix_material_subject_subject_id')

    op.drop_table('material_subject')
    op.drop_table('exam_result')
    op.drop_table('weekly_summary')
    op.drop_table('resource_slot_weekday')
    with op.batch_alter_table('record_comment', schema=None) as batch_op:
        batch_op.drop_index('ix_record_comment_daily_record_id')

    op.drop_table('record_comment')
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_index('ix_material_goal_id')
        batch_op.drop_index('ix_material_due_date')

    op.drop_table('material')
    with op.batch_alter_table('load_profile', schema=None) as batch_op:
        batch_op.drop_index('ix_load_profile_goal_period')

    op.drop_table('load_profile')
    with op.batch_alter_table('goal_retrospective', schema=None) as batch_op:
        batch_op.drop_index('ix_goal_retrospective_goal_generated')

    op.drop_table('goal_retrospective')
    with op.batch_alter_table('exam_subject', schema=None) as batch_op:
        batch_op.drop_index('ix_exam_subject_goal_id')

    op.drop_table('exam_subject')
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_message_record_sequence')

    op.drop_table('chat_message')
    op.drop_table('ai_conversation')
    op.drop_table('resource_slot')
    op.drop_table('prompt_template')
    op.drop_table('holiday')
    op.drop_table('goal')
    op.drop_table('day_type_default')
    op.drop_table('daily_record')
    op.drop_table('daily_message')
    op.drop_table('calendar_day_override')
    op.drop_table('app_setting')
    with op.batch_alter_table('ai_log', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_log_created_at')

    op.drop_table('ai_log')
    # ### end Alembic commands ###
